/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PopRouteImport } from './routes/pop'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgePackageIdRouteImport } from './routes/knowledge.$packageId'
import { Route as PopIndexRouteImport } from './routes/pop.index'
import { Route as PopPopIdRouteImport } from './routes/pop.$popId'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PopRoute = PopRouteImport.update({
  id: '/pop',
  path: '/pop',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgePackageIdRoute = KnowledgePackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const PopIndexRoute = PopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PopRoute,
} as any)
const PopPopIdRoute = PopPopIdRouteImport.update({
  id: '/$popId',
  path: '/$popId',
  getParentRoute: () => PopRoute,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/favoritos': typeof FavoritosRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/pop': typeof PopRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/knowledge/$packageId': typeof KnowledgePackageIdRoute
  '/pop/$popId': typeof PopPopIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pop/': typeof PopIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/favoritos': typeof FavoritosRoute
  '/knowledge/$packageId': typeof KnowledgePackageIdRoute
  '/pop/$popId': typeof PopPopIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/pop': typeof PopIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/favoritos': typeof FavoritosRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/pop': typeof PopRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/knowledge/$packageId': typeof KnowledgePackageIdRoute
  '/pop/$popId': typeof PopPopIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pop/': typeof PopIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/favoritos'
    | '/knowledge'
    | '/pop'
    | '/workspaces'
    | '/knowledge/$packageId'
    | '/pop/$popId'
    | '/workspaces/$workspaceId'
    | '/knowledge/'
    | '/pop/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/favoritos'
    | '/knowledge/$packageId'
    | '/pop/$popId'
    | '/workspaces/$workspaceId'
    | '/knowledge'
    | '/pop'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/favoritos'
    | '/knowledge'
    | '/pop'
    | '/workspaces'
    | '/knowledge/$packageId'
    | '/pop/$popId'
    | '/workspaces/$workspaceId'
    | '/knowledge/'
    | '/pop/'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  FavoritosRoute: typeof FavoritosRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  PopRoute: typeof PopRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pop': {
      id: '/pop'
      path: '/pop'
      fullPath: '/pop'
      preLoaderRoute: typeof PopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$packageId': {
      id: '/knowledge/$packageId'
      path: '/$packageId'
      fullPath: '/knowledge/$packageId'
      preLoaderRoute: typeof KnowledgePackageIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/pop/': {
      id: '/pop/'
      path: '/'
      fullPath: '/pop/'
      preLoaderRoute: typeof PopIndexRouteImport
      parentRoute: typeof PopRoute
    }
    '/pop/$popId': {
      id: '/pop/$popId'
      path: '/$popId'
      fullPath: '/pop/$popId'
      preLoaderRoute: typeof PopPopIdRouteImport
      parentRoute: typeof PopRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgePackageIdRoute: typeof KnowledgePackageIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgePackageIdRoute: KnowledgePackageIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface PopRouteChildren {
  PopPopIdRoute: typeof PopPopIdRoute
  PopIndexRoute: typeof PopIndexRoute
}

const PopRouteChildren: PopRouteChildren = {
  PopPopIdRoute: PopPopIdRoute,
  PopIndexRoute: PopIndexRoute,
}

const PopRouteWithChildren = PopRoute._addFileChildren(PopRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  FavoritosRoute: FavoritosRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  PopRoute: PopRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
