/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as ExecucaoRouteImport } from './routes/execucao'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PopRouteImport } from './routes/pop'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as ExecucaoIndexRouteImport } from './routes/execucao.index'
import { Route as ExecucaoInstanceIdRouteImport } from './routes/execucao.$instanceId'
import { Route as GovernancaIndexRouteImport } from './routes/governanca.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgePackageIdRouteImport } from './routes/knowledge.$packageId'
import { Route as PopIndexRouteImport } from './routes/pop.index'
import { Route as PopPopIdRouteImport } from './routes/pop.$popId'
import { Route as ProcessosIndexRouteImport } from './routes/processos.index'
import { Route as ProcessosProcessIdRouteImport } from './routes/processos.$processId'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as WorkflowWorkflowIdRouteImport } from './routes/workflow.$workflowId'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as PopPropostasProposalIdRouteImport } from './routes/pop.propostas.$proposalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecucaoRoute = ExecucaoRouteImport.update({
  id: '/execucao',
  path: '/execucao',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PopRoute = PopRouteImport.update({
  id: '/pop',
  path: '/pop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecucaoIndexRoute = ExecucaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecucaoRoute,
} as any)
const ExecucaoInstanceIdRoute = ExecucaoInstanceIdRouteImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => ExecucaoRoute,
} as any)
const GovernancaIndexRoute = GovernancaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovernancaRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgePackageIdRoute = KnowledgePackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const PopIndexRoute = PopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PopRoute,
} as any)
const PopPopIdRoute = PopPopIdRouteImport.update({
  id: '/$popId',
  path: '/$popId',
  getParentRoute: () => PopRoute,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcessosRoute,
} as any)
const ProcessosProcessIdRoute = ProcessosProcessIdRouteImport.update({
  id: '/$processId',
  path: '/$processId',
  getParentRoute: () => ProcessosRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowRoute,
} as any)
const WorkflowWorkflowIdRoute = WorkflowWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => WorkflowRoute,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const PopPropostasProposalIdRoute = PopPropostasProposalIdRouteImport.update({
  id: '/propostas/$proposalId',
  path: '/propostas/$proposalId',
  getParentRoute: () => PopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/execucao': typeof ExecucaoRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/governanca': typeof GovernancaRouteWithChildren
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/pop': typeof PopRouteWithChildren
  '/processos': typeof ProcessosRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/workflow': typeof WorkflowRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/execucao/$instanceId': typeof ExecucaoInstanceIdRoute
  '/knowledge/$packageId': typeof KnowledgePackageIdRoute
  '/pop/$popId': typeof PopPopIdRoute
  '/processos/$processId': typeof ProcessosProcessIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/execucao/': typeof ExecucaoIndexRoute
  '/governanca/': typeof GovernancaIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pop/': typeof PopIndexRoute
  '/processos/': typeof ProcessosIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/pop/propostas/$proposalId': typeof PopPropostasProposalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/favoritos': typeof FavoritosRoute
  '/inbox': typeof InboxRoute
  '/execucao/$instanceId': typeof ExecucaoInstanceIdRoute
  '/knowledge/$packageId': typeof KnowledgePackageIdRoute
  '/pop/$popId': typeof PopPopIdRoute
  '/processos/$processId': typeof ProcessosProcessIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/execucao': typeof ExecucaoIndexRoute
  '/governanca': typeof GovernancaIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/pop': typeof PopIndexRoute
  '/processos': typeof ProcessosIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/pop/propostas/$proposalId': typeof PopPropostasProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/execucao': typeof ExecucaoRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/governanca': typeof GovernancaRouteWithChildren
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/pop': typeof PopRouteWithChildren
  '/processos': typeof ProcessosRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/workflow': typeof WorkflowRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/execucao/$instanceId': typeof ExecucaoInstanceIdRoute
  '/knowledge/$packageId': typeof KnowledgePackageIdRoute
  '/pop/$popId': typeof PopPopIdRoute
  '/processos/$processId': typeof ProcessosProcessIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/execucao/': typeof ExecucaoIndexRoute
  '/governanca/': typeof GovernancaIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pop/': typeof PopIndexRoute
  '/processos/': typeof ProcessosIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/pop/propostas/$proposalId': typeof PopPropostasProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/execucao'
    | '/favoritos'
    | '/governanca'
    | '/inbox'
    | '/knowledge'
    | '/pop'
    | '/processos'
    | '/templates'
    | '/workflow'
    | '/workspaces'
    | '/execucao/$instanceId'
    | '/knowledge/$packageId'
    | '/pop/$popId'
    | '/processos/$processId'
    | '/templates/$templateId'
    | '/workflow/$workflowId'
    | '/workspaces/$workspaceId'
    | '/execucao/'
    | '/governanca/'
    | '/knowledge/'
    | '/pop/'
    | '/processos/'
    | '/templates/'
    | '/workflow/'
    | '/workspaces/'
    | '/pop/propostas/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/favoritos'
    | '/inbox'
    | '/execucao/$instanceId'
    | '/knowledge/$packageId'
    | '/pop/$popId'
    | '/processos/$processId'
    | '/templates/$templateId'
    | '/workflow/$workflowId'
    | '/workspaces/$workspaceId'
    | '/execucao'
    | '/governanca'
    | '/knowledge'
    | '/pop'
    | '/processos'
    | '/templates'
    | '/workflow'
    | '/workspaces'
    | '/pop/propostas/$proposalId'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/execucao'
    | '/favoritos'
    | '/governanca'
    | '/inbox'
    | '/knowledge'
    | '/pop'
    | '/processos'
    | '/templates'
    | '/workflow'
    | '/workspaces'
    | '/execucao/$instanceId'
    | '/knowledge/$packageId'
    | '/pop/$popId'
    | '/processos/$processId'
    | '/templates/$templateId'
    | '/workflow/$workflowId'
    | '/workspaces/$workspaceId'
    | '/execucao/'
    | '/governanca/'
    | '/knowledge/'
    | '/pop/'
    | '/processos/'
    | '/templates/'
    | '/workflow/'
    | '/workspaces/'
    | '/pop/propostas/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  ExecucaoRoute: typeof ExecucaoRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  GovernancaRoute: typeof GovernancaRouteWithChildren
  InboxRoute: typeof InboxRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  PopRoute: typeof PopRouteWithChildren
  ProcessosRoute: typeof ProcessosRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  WorkflowRoute: typeof WorkflowRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execucao': {
      id: '/execucao'
      path: '/execucao'
      fullPath: '/execucao'
      preLoaderRoute: typeof ExecucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pop': {
      id: '/pop'
      path: '/pop'
      fullPath: '/pop'
      preLoaderRoute: typeof PopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execucao/': {
      id: '/execucao/'
      path: '/'
      fullPath: '/execucao/'
      preLoaderRoute: typeof ExecucaoIndexRouteImport
      parentRoute: typeof ExecucaoRoute
    }
    '/execucao/$instanceId': {
      id: '/execucao/$instanceId'
      path: '/$instanceId'
      fullPath: '/execucao/$instanceId'
      preLoaderRoute: typeof ExecucaoInstanceIdRouteImport
      parentRoute: typeof ExecucaoRoute
    }
    '/governanca/': {
      id: '/governanca/'
      path: '/'
      fullPath: '/governanca/'
      preLoaderRoute: typeof GovernancaIndexRouteImport
      parentRoute: typeof GovernancaRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$packageId': {
      id: '/knowledge/$packageId'
      path: '/$packageId'
      fullPath: '/knowledge/$packageId'
      preLoaderRoute: typeof KnowledgePackageIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/pop/': {
      id: '/pop/'
      path: '/'
      fullPath: '/pop/'
      preLoaderRoute: typeof PopIndexRouteImport
      parentRoute: typeof PopRoute
    }
    '/pop/$popId': {
      id: '/pop/$popId'
      path: '/$popId'
      fullPath: '/pop/$popId'
      preLoaderRoute: typeof PopPopIdRouteImport
      parentRoute: typeof PopRoute
    }
    '/processos/': {
      id: '/processos/'
      path: '/'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof ProcessosRoute
    }
    '/processos/$processId': {
      id: '/processos/$processId'
      path: '/$processId'
      fullPath: '/processos/$processId'
      preLoaderRoute: typeof ProcessosProcessIdRouteImport
      parentRoute: typeof ProcessosRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/workflow/$workflowId': {
      id: '/workflow/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof WorkflowWorkflowIdRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/pop/propostas/$proposalId': {
      id: '/pop/propostas/$proposalId'
      path: '/propostas/$proposalId'
      fullPath: '/pop/propostas/$proposalId'
      preLoaderRoute: typeof PopPropostasProposalIdRouteImport
      parentRoute: typeof PopRoute
    }
  }
}

interface ExecucaoRouteChildren {
  ExecucaoInstanceIdRoute: typeof ExecucaoInstanceIdRoute
  ExecucaoIndexRoute: typeof ExecucaoIndexRoute
}

const ExecucaoRouteChildren: ExecucaoRouteChildren = {
  ExecucaoInstanceIdRoute: ExecucaoInstanceIdRoute,
  ExecucaoIndexRoute: ExecucaoIndexRoute,
}

const ExecucaoRouteWithChildren = ExecucaoRoute._addFileChildren(
  ExecucaoRouteChildren,
)

interface GovernancaRouteChildren {
  GovernancaIndexRoute: typeof GovernancaIndexRoute
}

const GovernancaRouteChildren: GovernancaRouteChildren = {
  GovernancaIndexRoute: GovernancaIndexRoute,
}

const GovernancaRouteWithChildren = GovernancaRoute._addFileChildren(
  GovernancaRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgePackageIdRoute: typeof KnowledgePackageIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgePackageIdRoute: KnowledgePackageIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface PopRouteChildren {
  PopPopIdRoute: typeof PopPopIdRoute
  PopIndexRoute: typeof PopIndexRoute
  PopPropostasProposalIdRoute: typeof PopPropostasProposalIdRoute
}

const PopRouteChildren: PopRouteChildren = {
  PopPopIdRoute: PopPopIdRoute,
  PopIndexRoute: PopIndexRoute,
  PopPropostasProposalIdRoute: PopPropostasProposalIdRoute,
}

const PopRouteWithChildren = PopRoute._addFileChildren(PopRouteChildren)

interface ProcessosRouteChildren {
  ProcessosProcessIdRoute: typeof ProcessosProcessIdRoute
  ProcessosIndexRoute: typeof ProcessosIndexRoute
}

const ProcessosRouteChildren: ProcessosRouteChildren = {
  ProcessosProcessIdRoute: ProcessosProcessIdRoute,
  ProcessosIndexRoute: ProcessosIndexRoute,
}

const ProcessosRouteWithChildren = ProcessosRoute._addFileChildren(
  ProcessosRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface WorkflowRouteChildren {
  WorkflowWorkflowIdRoute: typeof WorkflowWorkflowIdRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
}

const WorkflowRouteChildren: WorkflowRouteChildren = {
  WorkflowWorkflowIdRoute: WorkflowWorkflowIdRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
}

const WorkflowRouteWithChildren = WorkflowRoute._addFileChildren(
  WorkflowRouteChildren,
)

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  ExecucaoRoute: ExecucaoRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  GovernancaRoute: GovernancaRouteWithChildren,
  InboxRoute: InboxRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  PopRoute: PopRouteWithChildren,
  ProcessosRoute: ProcessosRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  WorkflowRoute: WorkflowRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
